/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "bitacora.h"

/*
 * Function that describes the conversion of a character pointer,
 * serving as a filter
 */
bool_t xdr_strinc(XDR * xdrs, char * p) {
	// Wraps the pointer filter into an exlusive character pointer filter
	if (!xdr_pointer(xdrs, p, sizeof(char), (xdrproc_t) xdr_char)) {
		return (FALSE);
	}
	
	return (TRUE);
}
